// Travel Context Graph — Neo4j Schema
// Constraints, indexes, and vector indexes for the travel customer service domain.
// Run once against your AuraDB instance before seeding data.

// ─── Constraints ──────────────────────────────────────────────────────────────

CREATE CONSTRAINT customer_id_unique      IF NOT EXISTS FOR (n:Customer)         REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT booking_id_unique       IF NOT EXISTS FOR (n:Booking)          REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT airline_id_unique       IF NOT EXISTS FOR (n:PartnerAirline)   REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT route_id_unique         IF NOT EXISTS FOR (n:Route)            REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT region_id_unique        IF NOT EXISTS FOR (n:Region)           REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT policy_id_unique        IF NOT EXISTS FOR (n:Policy)           REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT policy_section_id_unique IF NOT EXISTS FOR (n:PolicySection)   REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT carrier_agreement_id_unique IF NOT EXISTS FOR (n:CarrierAgreement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT weather_memo_id_unique  IF NOT EXISTS FOR (n:WeatherMemo)      REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT decision_id_unique      IF NOT EXISTS FOR (n:Decision)         REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT session_id_unique       IF NOT EXISTS FOR (n:Session)          REQUIRE n.id IS UNIQUE;

// ─── Range Indexes ─────────────────────────────────────────────────────────────

CREATE INDEX customer_loyalty_tier   IF NOT EXISTS FOR (n:Customer)   ON (n.loyalty_tier);
CREATE INDEX booking_status          IF NOT EXISTS FOR (n:Booking)    ON (n.status);
CREATE INDEX booking_departure       IF NOT EXISTS FOR (n:Booking)    ON (n.departure_date);
CREATE INDEX decision_type           IF NOT EXISTS FOR (n:Decision)   ON (n.decision_type);
CREATE INDEX decision_made_at        IF NOT EXISTS FOR (n:Decision)   ON (n.made_at);
CREATE INDEX weather_memo_active     IF NOT EXISTS FOR (n:WeatherMemo) ON (n.active);
CREATE INDEX region_code             IF NOT EXISTS FOR (n:Region)     ON (n.code);

// ─── Vector Indexes ────────────────────────────────────────────────────────────
// All use OpenAI text-embedding-3-small (1536 dims, cosine similarity).
// Created automatically by the backend on startup via vector_client.py.
// Run manually if you need them before the first backend start.

CREATE VECTOR INDEX policy_section_embeddings IF NOT EXISTS
FOR (n:PolicySection) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};

CREATE VECTOR INDEX carrier_agreement_embeddings IF NOT EXISTS
FOR (n:CarrierAgreement) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};

CREATE VECTOR INDEX weather_memo_embeddings IF NOT EXISTS
FOR (n:WeatherMemo) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};

// Decision node vector index — enables find_precedents() similarity search.
// Embeddings are generated by record_decision() at decision time.
CREATE VECTOR INDEX decision_embeddings IF NOT EXISTS
FOR (n:Decision) ON (n.embedding)
OPTIONS { indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};

// ─── Graph Data Model (reference) ─────────────────────────────────────────────
//
// (:Customer)-[:HAS_TIER]->(:LoyaltyTier)-[:GRANTS]->(:Benefit)
// (:Customer)-[:MADE]->(:Booking)-[:OPERATED_BY]->(:PartnerAirline)
// (:Booking)-[:ON_ROUTE]->(:Route)<-[:COVERS]-(:Region)
// (:Region)<-[:ACTIVE_FOR]-(:WeatherMemo)
// (:Booking)-[:GOVERNED_BY]->(:CarrierAgreement)
// (:Booking)-[:DISRUPTED_BY]->(:Event)
// (:Policy)-[:HAS_SECTION]->(:PolicySection)
// (:PolicySection)-[:REFERENCED_BY]->(:PolicySection)
// (:Session)-[:MADE_DECISION]->(:Decision)
// (:Decision)-[:BASED_ON]->(:PolicySection)
//
// Decision node properties:
//   id, decision_type, value (outcome), reasoning,
//   confidence_score (0.0-1.0), risk_factors (list),
//   policy_citations (list of IDs), embedding (1536-dim), made_at
