/**
 * Domain configuration for Hospitality
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "travel-customer-service",
  name: "Travel",
  description: "Customer service intelligence for flight disruptions, refunds, and policy resolution",
  tagline: "GraphRAG-powered Customer Service Agent",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {
  "Customer": "#3b82f6",
  "Booking": "#22c55e",
  "PartnerAirline": "#f97316",
  "Route": "#0891b2",
  "LoyaltyTier": "#a855f7",
  "Benefit": "#eab308",
  "PolicySection": "#dc2626",
  "Policy": "#ef4444",
  "CarrierAgreement": "#1e40af",
  "WeatherMemo": "#6366f1",
  "Event": "#f97316",
  "Region": "#84cc16",
  "Session": "#94a3b8",
  "Decision": "#16a34a",
};

export const NODE_SIZES: Record<string, number> = {
  "Customer": 28,
  "Booking": 22,
  "PartnerAirline": 25,
  "Route": 18,
  "LoyaltyTier": 20,
  "Benefit": 16,
  "PolicySection": 20,
  "Policy": 24,
  "CarrierAgreement": 22,
  "WeatherMemo": 22,
  "Event": 20,
  "Region": 18,
  "Session": 18,
  "Decision": 24,
};

export const DEFAULT_CYPHER = `MATCH (c:Customer)-[:MADE]->(b:Booking)-[:OPERATED_BY]->(a:PartnerAirline) RETURN c, b, a LIMIT 50`;

export const SCHEMA_NODE_SIZE = 18;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    name: "Disruption & Refunds",
    prompts: [
      "Process a refund for Sarah Chen on booking EXP-991 — her Maui flight was canceled due to the Pacific storm",
      "What refund is James Okafor entitled to for his disrupted booking EXP-887?",
    ]
  },
  {
    name: "Multi-hop GraphRAG",
    prompts: [
      "Which customers affected by the Pacific storm qualify for the automatic $50 Platinum goodwill credit?",
      "Tom Reyes wants to cancel his ORD→Miami booking — what cancellation fees apply given his Blue tier and no active weather waiver on that route?",
      "What is the fastest possible refund timeline for Sarah Chen on EXP-991, combining her Gold status, the Alaska Airlines agreement, and the active Pacific storm waiver?",
      "If Maya Patel's ORD→Miami flight gets disrupted, is there any active weather waiver covering her route, and what would her Silver tier entitle her to?"
    ]
  },
  {
    name: "Policy Lookup",
    prompts: [
      "Is there an active weather waiver affecting Alaska Airlines flights to Hawaii?",
      "What is the refund policy for involuntary cancellations?",
      "What fee waivers apply to Gold loyalty members?",
      "What are the refund terms under the Alaska Airlines carrier agreement?"
    ]
  },
  {
    name: "Customer Intelligence",
    prompts: [
      "Show me all Gold and Platinum customers with their disrupted bookings",
      "Which customers have points+cash mixed payment bookings affected by the Pacific storm?",
      "What past refund decisions have been recorded for storm cancellations?"
    ]
  }
];
